<template>
  <div class="reset-password-page">
    <h1 class="page-title">Reset Password</h1>
    <div v-if="error" class="error-message">{{ error }}</div>
    <form @submit.prevent="resetPassword()">
      <div class="input-box">
        <label for="email">Email</label>
        <input
          id="email"
          v-model="email"
          type="email"
          placeholder="Enter your email"
        />
      </div>

      <svg
        v-if="sendingEmail"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        style="
          margin: auto;
          background: rgb(255, 255, 255);
          display: block;
          shape-rendering: auto;
        "
        width="20px"
        height="20px"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
      >
        <circle
          cx="50"
          cy="50"
          fill="none"
          stroke="#ff0011"
          stroke-width="10"
          r="35"
          stroke-dasharray="164.93361431346415 56.97787143782138"
        >
          <animateTransform
            attributeName="transform"
            type="rotate"
            repeatCount="indefinite"
            dur="1s"
            values="0 50 50;360 50 50"
            keyTimes="0;1"
          ></animateTransform>
        </circle>
        <!-- [ldio] generated by https://loading.io/ -->
      </svg>

      <button v-else type="submit" class="primary-btn-full-width">Send</button>

      <p class="text">We will send you a reset link on your mail.</p>
    </form>
  </div>
</template>

<script>
export default {
  layout: 'footer-less',
  data() {
    return {
      email: '',
      error: '',
      sendingEmail: false,
    }
  },
}
</script>

<style lang="scss" scoped>
@import '~/styles/style.scss';

.reset-password-page {
  @extend .flex;
  flex-direction: column;
  font-family: $font-primary;
  background: #f1f1f9;
  min-height: calc(100vh - 4rem);
  .page-title {
    font-size: 2.1rem;
    text-transform: capitalize;
    color: #004b63;
    margin-bottom: 1.6rem;
    @include responsive(phone) {
      font-size: 1.5rem;
    }
  }
  .error-message {
    margin-bottom: 1rem;
    color: red;
    max-width: 500px;
    line-height: 1.6;
  }
  form {
    width: 407px;
    display: flex;
    flex-direction: column;
    padding: 2.3rem 1.8rem;
    @extend .primary-shadow;
    @include responsive(phone) {
      padding: 2rem 1.5rem;
    }
    .input-box {
      margin-bottom: 1rem;
    }
    .pd-8 {
      padding: 0.7rem 0.75rem;
    }
    .text {
      text-align: center;
      padding-top: 0.7rem;
      font-size: 0.9rem;
      color: #004b63;
    }
    .border {
      border: none;
    }
  }
}
</style>
